minimumReleaseAgeExclude:
  - '@eslint-react/ast@5.8.17'
  - '@eslint-react/core@5.8.17'
  - '@eslint-react/eslint-plugin@5.8.17'
  - '@eslint-react/eslint@5.8.17'
  - '@eslint-react/jsx@5.8.17'
  - '@eslint-react/shared@5.8.17'
  - '@eslint-react/var@5.8.17'
  - '@next/env@16.2.9'
  - '@next/swc-darwin-arm64@16.2.9'
  - '@next/swc-darwin-x64@16.2.9'
  - '@next/swc-linux-arm64-gnu@16.2.9'
  - '@next/swc-linux-arm64-musl@16.2.9'
  - '@next/swc-linux-x64-gnu@16.2.9'
  - '@next/swc-linux-x64-musl@16.2.9'
  - '@next/swc-win32-arm64-msvc@16.2.9'
  - '@next/swc-win32-x64-msvc@16.2.9'
  - eslint-plugin-react-dom@5.8.17
  - eslint-plugin-react-jsx@5.8.17
  - eslint-plugin-react-naming-convention@5.8.17
  - eslint-plugin-react-rsc@5.8.17
  - eslint-plugin-react-web-api@5.8.17
  - eslint-plugin-react-x@5.8.17
  - next@16.2.9
  - fumadocs-core@16.10.0
  - fumadocs-mdx@15.0.12
  - fumadocs-ui@16.10.0
shellEmulator: true
packages:
  - seitu
  - docs
  - playground
allowBuilds:
  esbuild: false
  sharp: false
